id: taxonomy_term.full
uuid: db8a8950-3ab9-446c-a351-81989fdf8d49
label: 'Taxonomy term page'
targetEntityType: taxonomy_term
status: true
cache: true
langcode: und
dependencies:
  module:
    - taxonomy
