id: notification_entity.rss
uuid: 397a4093-7ed5-4753-a100-bfb015cbc325
label: RSS
targetEntityType: notification_entity
status: false
cache: true
langcode: und
dependencies:
  module:
    - notification_entity
