id: taxonomy_term.full
uuid: 37755f50-9b3b-4a79-bb3e-620b444c8fa0
label: 'Taxonomy term page'
targetEntityType: taxonomy_term
status: true
cache: true
langcode: und
dependencies:
  module:
    - taxonomy
