id: notification_entity.full
uuid: b05449d6-126d-4910-a45b-912dfb583d50
label: 'Full content'
targetEntityType: notification_entity
status: false
cache: true
langcode: und
dependencies:
  module:
    - notification_entity
